# Generated by Django 6.0.2 on 2026-02-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('FACULTY', 'Faculty'), ('STUDENT', 'Student'), ('ACCOUNTANT', 'Accountant')], default='ADMIN', max_length=50),
        ),
    ]
