# Generated by Django 6.0.2 on 2026-02-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_feepayment_collected_by_feepayment_payment_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepayment',
            name='collected_by',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='receipt_no',
        ),
    ]
