# Generated by Django 6.0.2 on 2026-02-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversitySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(default='My University', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/')),
                ('academic_year', models.CharField(default='2024-2025', max_length=20)),
                ('current_semester', models.IntegerField(default=1)),
            ],
        ),
    ]
