# Generated by Django 6.0.2 on 2026-02-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='room_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
