# Generated by Django 6.0.2 on 2026-02-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0002_exam_end_time_exam_is_published_exam_room_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='start_time',
        ),
    ]
