# Generated by Django 6.0.2 on 2026-02-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0003_remove_exam_end_time_remove_exam_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='room_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
