# Generated by Django 6.0.2 on 2026-02-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='capacity',
        ),
    ]
